# Custom Language File for Launcher Customizer

[ejs.app]
title = "Pooh server"

[ejs.landing]
mediaGitHubURL = "https://github.com/ii109/PoohServer"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/ii109/PoohServer"
supportLink = "https://github.com/ii109/PoohServer/issues"

[ejs.welcome]
welcomeHeader = "welcome To Pooh server"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
